import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { analyze } from "../../dist/core/index.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Colors for console logging
const green = (t) => `\x1b[32m${t}\x1b[0m`;
const red = (t) => `\x1b[31m${t}\x1b[0m`;
const blue = (t) => `\x1b[34m${t}\x1b[0m`;
const dim = (t) => `\x1b[2m${t}\x1b[0m`;

async function main() {
  console.log(blue("🛡️  DiffGate — Agent Self-Correction Demo\n"));

  // 1. Initial Unsafe Code Generated by LLM
  const unsafeCode = `// Autogenerated database query
function getUser(req, res) {
  const query = "SELECT * FROM users WHERE id = " + req.query.id;
  db.query(query, (err, user) => {
    res.json(user);
  });
}
`;

  console.log(dim("=== Step 1: Agent generates draft code ==="));
  console.log(unsafeCode);

  // 2. Run DiffGate check via the core analyzer
  console.log(dim("=== Step 2: Agent runs DiffGate check on the code draft ==="));
  
  const testFile = path.join(__dirname, "temp_query.js");
  fs.writeFileSync(testFile, unsafeCode);

  const res1 = analyze({
    filePath: testFile,
    content: unsafeCode,
    config: { rules: {} }
  });

  if (res1.findings.length > 0) {
    console.log(red(`❌ Scan Failed — Detected ${res1.findings.length} findings:`));
    for (const f of res1.findings) {
      console.log(`  - [Line ${f.line}] ${red(f.title)} (${f.ruleId}): ${f.message}`);
    }
    console.log();
  }

  // 3. Simulating Agent Self-Correction (Self-Healing Loop)
  console.log(dim("=== Step 3: Agent parses JSON error and self-corrects the code ==="));
  console.log(blue("🤖 Agent Thinking: \"DiffGate flagged a SQL injection on Line 3. I will parameterize the query to secure it.\""));
  
  const safeCode = `// Autogenerated database query (Corrected by DiffGate)
function getUser(req, res) {
  const query = "SELECT * FROM users WHERE id = ?";
  db.query(query, [req.query.id], (err, user) => {
    res.json(user);
  });
}
`;

  console.log(`\n${safeCode}`);

  // 4. Re-run DiffGate scan to verify safety
  console.log(dim("=== Step 4: Agent re-runs DiffGate scan on corrected code ==="));
  
  const res2 = analyze({
    filePath: testFile,
    content: safeCode,
    config: { rules: {} }
  });

  const hasOrange = res2.findings.some(f => f.tier === "orange");
  if (!hasOrange) {
    console.log(green("✓ Scan Passed — High-impact SQL injection resolved! Code is safe to write to disk. ✨"));
    if (res2.findings.length > 0) {
      console.log(dim(`  (Note: DiffGate still returned ${res2.findings.length} yellow/green soft warning(s) for review)`));
      for (const f of res2.findings) {
        console.log(dim(`    - [Line ${f.line}] ${f.title} (${f.ruleId})`));
      }
    }
    console.log();
  } else {
    console.log(red("❌ Scan still failed — orange findings remain."));
  }

  // Cleanup temporary file
  try {
    fs.unlinkSync(testFile);
  } catch {}
}

main();
